CertiPower/Controllers/RecordController.cs
using BLL;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CertiPower.Controllers
{
    public class RecordController : Controller
    {
        // GET: Record
        public ActionResult Index()
        {
            Record model = new Record();
            return View(model);
        }

        [HttpPost]
        public ActionResult Save(Record record, HttpPostedFileBase postedFiles)
        {
            string msg = string.Empty;
            //if (string.IsNullOrEmpty(record.FileName))
            //{
            //    if (postedFiles == null || postedFiles.ContentLength == 0)
            //    {
            //        TempData["Error"] = "Please upload files.";
            //        return RedirectToAction("Index");
            //    }
            //}
            
            if (postedFiles != null && postedFiles.ContentLength > 0)
            {
                string timestamp = DateTime.Now.ToString("yyyyMMddHHmmss");
                string extension = System.IO.Path.GetExtension(postedFiles.FileName);
                if (extension == ".pdf" || extension == ".doc" || extension == ".docx" || extension == ".xlsx")
                {
                    string fileName = timestamp + System.IO.Path.GetExtension(postedFiles.FileName);
                    postedFiles.SaveAs(Server.MapPath("~/App_Shared/Files/" + fileName));
                    record.FileName = fileName;
                    record.OriginalFileName = postedFiles.FileName;
                }
                else
                {
                    TempData["Error"] = "Only .pdf,.doc and .xlsx formats are allowed.";
                    return RedirectToAction("Index");
                }
            }
            record.Date = DateTime.Now;
            record.OrganizationId = new Account().FetchOrganization().OrganizationId;
            if (record.Id == 0)
            {
                if (new ManageRecord().AddRecord(record))
                {
                    msg = "Record has been added successfully";
                }
            }
            else
            {
                if (new ManageRecord().UpdateRecord(record))
                {
                    msg = "Record has been update successfully.";
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult FetchById(int recordId)
        {
            DAL.Record record = new ManageRecord().FetchRecordById(recordId);
            //record.Active = record.IsActive.HasValue ? record.IsActive.Value : false;
            return PartialView("_Record", record);
        }
        public JsonResult Delete(int Id)
        {
            string msg = string.Empty;
            if (new ManageRecord().Delete(Id))
            {
                msg = "Record has been deleted successfully.";
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Fetch(Paging paging, SearchDepartment departSearch)
        {
            departSearch.OrganizationId = new Account().FetchOrganization().OrganizationId;
            object gridData;
            try
            {
                List<FetchRecord_Result> list = new ManageRecord().FetchRecords(paging, departSearch);

                gridData = new
                {
                    data = list.ToArray(),

                    itemsCount = list.Count > 0 ? list.FirstOrDefault().TotalRecord : 0
                };


            }
            catch (Exception e)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }

            return Json(gridData, JsonRequestBehavior.AllowGet);
        }
        //public JsonResult FetchFolders()
        //{
        //    return Json(new ManageFolder().FetchFolder(), JsonRequestBehavior.AllowGet);
        //}
        public ActionResult OpenModal()
        {
            return PartialView("_Record", new Record());
        }
        public FileResult DownLoadFile(string file)
        {
            string contentType = string.Empty;
            if (file.Contains(".pdf"))
            {
                contentType = "application/pdf";
            }
            else if (file.Contains(".doc") || file.Contains(".docx"))
            {
                contentType = "application/doc";
            }
            else if (file.Contains(".xlsx") || file.Contains(".xls"))
            {
                contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            }
            return File(Server.MapPath("~/App_Shared/Files/" + file), contentType, file);
        }
    }
}

CertiPower/Views/Record/Index.cshtml
@{
    ViewBag.Title = "Manage Record";
}

@Scripts.Render("~/AngularJsGrid/jquery")

<div class="row" ng-controller="RecordCTRL">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="row">
                <div class="col-sm-12">
                   @if (TempData["Error"] != null)
                   {
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>Error!</strong> @TempData["Error"]
                    </div>
                   }
                </div>
            </div>
        </div>
        <div class="form-group">

            <div class="panel">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-2">
                            File Name
                            <input type="text" ng-model="departSearch.Name" class="form-control" />
                        </div>
                        <div class="col-sm-2">
                            Folder
                            <select ng-model="departSearch.FolderId" class="form-control">
                                <option value="">All</option>
                                <option ng-repeat="x in searchFolder" value="{{x.Id}}">{{x.Name}}</option>
                            </select>
                        </div>
                        <div class="col-sm-1">
                            <br />
                            <button class="btn btn-success" ng-click="Search();"><i class="fa fa-search"></i> Search</button>
                        </div>
                        <div class="col-sm-7">
                            <br />
                            <a ng-click="DepartmentOpenModel();" class="pull-right btn btn-primary"><i class="fa fa-plus"></i> Add Record</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-sm-12">
                    <div id="recordGrid"></div>
                </div>

            </div>
        </div>
        <div id="dvRecordDetail">
            @Html.Partial("_Record")
        </div>
    </div>

</div>

CertiPower/Views/Record/_Record.cshtml
@model DAL.Record
<script src="~/Angular/Record.js"></script>
<link href="~/js/jquery-ui-1.10.3.custom/css/custom-theme/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" />
<div id="RecordModal" class="modal fade" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Manage Record</h4>
            </div>
            <div class="modal-body clearfix">
                @using (Html.BeginForm("Save", "Record", FormMethod.Post, new { role = "form", enctype = "multipart/form-data", encoding = "multipart/form-data" }))
                {
                    @Html.HiddenFor(s => s.Id)
                    <div class="form-group">
                        <label for="AgreedActionText">Folder<span style="color:red"> *</span></label>
                        @Html.DropDownListFor(p => p.FolderId, new SelectList(new BLL.ManageFolder().FetchFolder(new Account().FetchOrganization().OrganizationId), "ID", "Name"), "Please Select", new { @class = "form-control", @required="required" })
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <label for="AgreedActionText">File Name</label>
                                @*@Html.TextBoxFor(p => p.OriginalFileName,new { @class="form-control",@name= "postedFiles",type="file", accept = ".doc,.pdf,.xls,.xlsx" })*@
                                <input type="file" accept=".doc,.docx,.pdf,.xls,.xlsx" name="postedFiles" id="file" maxlength="100" value="" class="form-control" />
                                @Html.HiddenFor(s => s.FileName)
                                @Html.HiddenFor(s => s.OriginalFileName)
                            </div>
                            <div class="col-sm-6">
                                <br />
                                <a href="@Url.Action("DownLoadFile","Record",new {file = Model.FileName })">@Model.OriginalFileName</a>
                            </div>
                        </div>
                        
                    </div>
                    <div class="form-group">
                        <label for="AgreedActionText">File Description</label>
                        @Html.TextAreaFor(p => p.FileDescription,new { @class="form-control"})
                        @*<textarea ng-model="depart.FileDescription" name="txtname" maxlength="100" value="" class="form-control"></textarea>*@
                    </div>
                    <div class="form-group">
                        <label for="AgreedActionText">Invoice Amount<span style="color:red"> *</span></label>
                        @*<input type="text" ng-model="depart.InvoiceAmount" name="txtname" maxlength="100" value="" class="form-control number" required />*@
                        @Html.TextBoxFor(p => p.InvoiceAmount,new { @class="form-control", @required = "required" })
                    </div>
                    <div class="form-group">
                        <label for="AgreedActionText">Receive From</label>
                        @Html.TextBoxFor(p => p.ReceiveFrom, new { @class = "form-control", @required = "required" })
                    </div>
                    <div class="form-group">
                        <label for="AgreedActionText">Sent To</label>
                        @Html.TextBoxFor(p => p.SentTo, new { @class = "form-control", @required = "required" })
                    </div>
                    <div class="form-group">
                        <label for="AgreedActionText">Priority<span style="color:red"> *</span></label>
                        @Html.DropDownListFor(p => p.Priority, new SelectList(new BLL.GenericMethods().FetchPriority(), "Name", "Name"), "Please Select", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <div class="pull-right">
                            <input type="submit" name="name" value="Save" class="btn btn-success" />
                            <a class="btn btn-sm btn-success" data-dismiss="modal"><i class="fa fa-crosshairs"></i> Close</a>
                        </div>
                    </div>
                }
               
            </div>
        </div>
    </div>
</div>