CertiPower/Controllers/AgreementController.cs
using BLL;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CertiPower.Controllers
{
    public class AgreementController : Controller
    {
        // GET: Agreement
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddAgreement(int? Id)
        {
            if(Id.HasValue)
            {
                Agreement agreement = new ManageAgreement().FetchAgreementById(Id.Value);
                agreement.OrganizationId = agreement.OrgInstituteAgreements.FirstOrDefault().OrganizationId.Value;
                agreement.InstituteId = agreement.OrgInstituteAgreements.FirstOrDefault().InstituteId.Value;
                return View(agreement);
            }
            return View();
        }

        public ActionResult Fetch(Paging paging, SearchDepartment departSearch)
        {
            object gridData;
            try
            {
                List<FetchAgreement_Result> list = new ManageAgreement().FetchAgreements(paging, departSearch);

                gridData = new
                {
                    data = list.ToArray(),

                    itemsCount = list.Count > 0 ? list.FirstOrDefault().TotalRecord : 0
                };


            }
            catch (Exception e)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }

            return Json(gridData, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult AddAgreement(Agreement agreement)
        {
            //org.IsOrganization = true;
            OrgInstituteAgreement newAgreement = new OrgInstituteAgreement();
            newAgreement.OrganizationId = agreement.OrganizationId;
            newAgreement.InstituteId = agreement.InstituteId;
            
            if (agreement.Id != 0)
            {
                agreement.OrgInstituteAgreements.Add(newAgreement);
                if (new ManageAgreement().UpdateAgreement(agreement))
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                agreement.OrgInstituteAgreements.Add(newAgreement);
                if (new ManageAgreement().AddAgreement(agreement))
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult AgreementStudents()
        {
            AgreementViewModel model = new AgreementViewModel();
            List<Student> lstStudent = new List<Student>();
            model.lstStudent = lstStudent;
            return View(model);
        }

        [HttpPost]
        public ActionResult FetchStudents(int? Id)
        {
            int noOfStudents = 0;
            AgreementViewModel model = new AgreementViewModel();
            Agreement agr = new Agreement();
            List<Student> lstAgreementStudent = new List<Student>();
            if (Id.HasValue)
            {
                agr = new ManageAgreement().FetchAgreementStudentCount(Id.Value);
            }
            List<Student> lstStudent = new List<Student>();
            Student std;
            if (agr.Students != null && agr.Students.Count > 0)
            {
                lstAgreementStudent = agr.Students.Where(s => s.IsActive == true).ToList();
                foreach (var item in lstAgreementStudent)
                {
                    lstStudent.Add(item);
                }
            }

            int? remainingStudent = agr.TraineeNumber - agr.Students.Where(s => s.IsActive == true).Count();
            for (int i = 0; i < remainingStudent; i++)
            {
                std = new Student();
                lstStudent.Add(std);
            }
            
            model.lstStudent = lstStudent;
            return PartialView("_AgreementStudents", model);
        }

        [HttpPost]
        public ActionResult SaveStudents(AgreementViewModel model)
        {
            model.lstStudent.ForEach(s => s.AgreementId = model.AgreementId);
            if (new ManageStudent().AddUpdateStudent(model.lstStudent))
            {
                return RedirectToAction("AgreementStudents");
            }
            return View();
        }
    }
}

CertiPower/Views/Agreement/AgreementStudents.cshtml
@model DAL.AgreementViewModel
@{
    ViewBag.Title = "Agreement Students";
}
@Scripts.Render("~/AngularJsGrid/jquery")
<div class="row">
    <div class="col-sm-12">
        <div class="panel">
            @using (Html.BeginForm("SaveStudents", "Agreement", FormMethod.Post, new { }))
            {
                <div class="panel-body clearfix">
                    <div class="form-group">
                        <div class="col-sm-3">
                            Agreement
                            @Html.DropDownListFor(p => p.AgreementId, new SelectList(new BLL.ManageOrganization().FetchAgreementById(new Account().FetchOrganization().OrganizationId), "Id", "Name"), "Please Select", new { @id = "ddlAgreements", @class = "form-control", @required = "required" })
                        </div>
                        <div class="col-sm-9"></div>
                    </div>
                    <div class="form-group">
                        <div id="dvStudents">
                            @Html.Partial("_AgreementStudents", Model)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <div class="pull-right">
                                <button type="submit" class="btn btn-success">Approve</button>
                                <a class="btn btn-default" onclick="location.reload();">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>

    </div>
</div>
<script>
    $(document).on("change", "#ddlAgreements", function () {
        var agreementId = $(this).val();
        $.ajax({
            url: '/Agreement/FetchStudents',
            type: 'Post',
            data: { Id: agreementId },
            success: function (result) {
                $("#dvStudents").html(result);
            }
        });
    });
</script>

CertiPower/Views/Agreement/Index.cshtml
@{
    ViewBag.Title = "Manage Agreement";
}

@Scripts.Render("~/AngularJsGrid/jquery")
<script src="~/Angular/Agreement.js"></script>
<div class="row" ng-controller="agreementCTRL">
    <div class="col-sm-12">
        <div class="form-group">

            <div class="panel">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-2">
                            Name
                            <input type="text" ng-model="departSearch.Name" class="form-control" />
                        </div>
                        <div class="col-sm-1">
                            <br />
                            <button class="btn btn-success" ng-click="Search();"><i class="fa fa-search"></i> Search</button>
                        </div>
                        <div class="col-sm-9">
                            <br />
                            <a href="/Agreement/AddAgreement" class="pull-right btn btn-primary"><i class="fa fa-plus"></i> Add Agreement</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-sm-12">
                    <div id="agreementGrid"></div>
                </div>
            </div>
        </div>
    </div>

</div>

CertiPower/Views/Agreement/_AgreementStudents.cshtml
@model DAL.AgreementViewModel
<br />
<br />
<div class="panel">
    @if (Model.lstStudent.Count > 0)
    {
        <div class="panel-heading">
            <h3><strong>Students Detail</strong></h3>
        </div>
    }
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="col-sm-3"></div>
                <div class="col-sm-3"></div>
                <div class="col-sm-3"></div>
                <div class="col-sm-3"></div>
            </div>
        </div>
        @for (int i = 0; i < Model.lstStudent.Count; i++)
        {
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-3">
                        @Html.HiddenFor(s => s.lstStudent[i].Id)
                        <div class="form-group">
                            Student Name
                            @Html.TextBoxFor(s => s.lstStudent[i].Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(s => s.lstStudent[i].Name)
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            Father Name
                            @Html.TextBoxFor(s => s.lstStudent[i].FatherName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(s => s.lstStudent[i].FatherName)
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            CNIC
                            @Html.TextBoxFor(s => s.lstStudent[i].CNIC, new { @class = "form-control" })
                            @Html.ValidationMessageFor(s => s.lstStudent[i].CNIC)
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <br />
                        <div class="form-group">
                            <div class="col-sm-6">
                                Status
                            </div>
                            <div class="col-sm-6">
                                @Html.CheckBoxFor(s => s.lstStudent[i].IsActive, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>